app = "macromuscles-backend"
primary_region = "iad"

[build]

[env]
  PORT = "3000"

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "requests"

  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    method = "get"
    path = "/api/health"
    protocol = "http"
    tls_skip_verify = false

